global:
  scrape_interval:     1s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.


scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'node'
    scrape_interval: 5s
    static_configs:
      - targets: ['172.18.0.12:9100']

  - job_name: 'postgres'
    scrape_interval: 5s
    static_configs:
      - targets: ['172.18.0.13:9187']   

  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
      - targets: ['cadvisor:8080']
